[package]
name = "youki"
version = "0.0.3"
description = "A container runtime written in Rust"
license-file = "../../LICENSE"
repository = "https://github.com/containers/youki"
homepage = "https://containers.github.io/youki"
readme = "../../README.md"
authors = ["youki team"]
edition = "2021"
build = "build.rs"
keywords = ["youki", "container"]

[features]
systemd = ["libcgroups/systemd", "libcontainer/systemd", "v2"]
v2 = ["libcgroups/v2", "libcontainer/v2"]
v1 = ["libcgroups/v1", "libcontainer/v1"]
cgroupsv2_devices = ["libcgroups/cgroupsv2_devices", "libcontainer/cgroupsv2_devices"]

[dependencies.clap]
version = "3.2.23"
default-features = false
features = ["std", "suggestions", "derive", "cargo"]

[dependencies]
anyhow = "1.0.65"
chrono = { version = "0.4", features = ["serde"] }
libcgroups = { version = "0.0.3", path = "../libcgroups", default-features = false }
libcontainer = { version = "0.0.3", path = "../libcontainer", default-features = false }
liboci-cli = { version = "0.0.3", path = "../liboci-cli" }
log = { version = "0.4", features = ["std"] }
nix = "0.25.0"
oci-spec = { version = "0.5.8", features = ["runtime"] }
once_cell = "1.16.0"
pentacle = "1.0.0"
procfs = "0.14.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tabwriter = "1"
clap_complete = "4.1.1"

[dev-dependencies]
serial_test = "0.9.0"

[build-dependencies]
anyhow = "1.0.65"
vergen = "7.2.1"
